// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef chat_h
#define chat_h
#include <FL/Fl.H>
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *msg_in;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Text_Editor.H>
extern "C" { int main(); }
#endif
