// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include <FL/Fl.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Text_Buffer.H>


int main() {
  Fl_Window *win = new Fl_Window(0, 0, 640, 480, "BChat");
  Fl_Text_Buffer  *buffer   = new Fl_Text_Buffer;
  Fl_Text_Editor  *editor   = new Fl_Text_Editor(10, 370, 530, 100);
  Fl_Text_Display *msg_dps  = new Fl_Text_Display(10, 10, 620, 340);
  Fl_Button       *send_bnt = new Fl_Button(550, 380, 80, 80, "Send");
  
  
  editor->buffer(buffer);
  editor->wrap_mode(Fl_Text_Editor::WRAP_AT_BOUNDS, 0);

  win->show();
  
  return Fl::run(); 
}
